name: Github Actions Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Setup
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236
        with:
          node-version: 16.14.0
      - name: Cache NPM packages
        uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test
